revoke delete on table "public"."testMig" from "anon";

revoke insert on table "public"."testMig" from "anon";

revoke references on table "public"."testMig" from "anon";

revoke select on table "public"."testMig" from "anon";

revoke trigger on table "public"."testMig" from "anon";

revoke truncate on table "public"."testMig" from "anon";

revoke update on table "public"."testMig" from "anon";

revoke delete on table "public"."testMig" from "authenticated";

revoke insert on table "public"."testMig" from "authenticated";

revoke references on table "public"."testMig" from "authenticated";

revoke select on table "public"."testMig" from "authenticated";

revoke trigger on table "public"."testMig" from "authenticated";

revoke truncate on table "public"."testMig" from "authenticated";

revoke update on table "public"."testMig" from "authenticated";

revoke delete on table "public"."testMig" from "service_role";

revoke insert on table "public"."testMig" from "service_role";

revoke references on table "public"."testMig" from "service_role";

revoke select on table "public"."testMig" from "service_role";

revoke trigger on table "public"."testMig" from "service_role";

revoke truncate on table "public"."testMig" from "service_role";

revoke update on table "public"."testMig" from "service_role";

alter table "public"."testMig" drop constraint "testMig_pkey";

drop index if exists "public"."testMig_pkey";

drop table "public"."testMig";

create table "public"."all" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "test" text
);


alter table "public"."all" enable row level security;

CREATE UNIQUE INDEX all_pkey ON public."all" USING btree (id);

alter table "public"."all" add constraint "all_pkey" PRIMARY KEY using index "all_pkey";

grant delete on table "public"."all" to "anon";

grant insert on table "public"."all" to "anon";

grant references on table "public"."all" to "anon";

grant select on table "public"."all" to "anon";

grant trigger on table "public"."all" to "anon";

grant truncate on table "public"."all" to "anon";

grant update on table "public"."all" to "anon";

grant delete on table "public"."all" to "authenticated";

grant insert on table "public"."all" to "authenticated";

grant references on table "public"."all" to "authenticated";

grant select on table "public"."all" to "authenticated";

grant trigger on table "public"."all" to "authenticated";

grant truncate on table "public"."all" to "authenticated";

grant update on table "public"."all" to "authenticated";

grant delete on table "public"."all" to "service_role";

grant insert on table "public"."all" to "service_role";

grant references on table "public"."all" to "service_role";

grant select on table "public"."all" to "service_role";

grant trigger on table "public"."all" to "service_role";

grant truncate on table "public"."all" to "service_role";

grant update on table "public"."all" to "service_role";
