
create table "public"."all" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "newAt" text,
    "we" text
);


alter table "public"."all" enable row level security;

CREATE UNIQUE INDEX all_pkey ON public."all" USING btree (id);

alter table "public"."all" add constraint "all_pkey" PRIMARY KEY using index "all_pkey";

grant delete on table "public"."all" to "anon";

grant insert on table "public"."all" to "anon";

grant references on table "public"."all" to "anon";

grant select on table "public"."all" to "anon";

grant trigger on table "public"."all" to "anon";

grant truncate on table "public"."all" to "anon";

grant update on table "public"."all" to "anon";

grant delete on table "public"."all" to "authenticated";

grant insert on table "public"."all" to "authenticated";

grant references on table "public"."all" to "authenticated";

grant select on table "public"."all" to "authenticated";

grant trigger on table "public"."all" to "authenticated";

grant truncate on table "public"."all" to "authenticated";

grant update on table "public"."all" to "authenticated";

grant delete on table "public"."all" to "service_role";

grant insert on table "public"."all" to "service_role";

grant references on table "public"."all" to "service_role";

grant select on table "public"."all" to "service_role";

grant trigger on table "public"."all" to "service_role";

grant truncate on table "public"."all" to "service_role";

grant update on table "public"."all" to "service_role";
