name: Backup Supabase Full Database
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  backup-full-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PostgreSQL Apt Repository for v17
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

      - name: Install PostgreSQL 17 client tools
        run: sudo apt-get install -y postgresql-client-17

      - name: Backup full database (schema + data) with compression
        id: backup
        env:
          DB_HOST: ${{ secrets.PROD_DB_HOST }}
          DB_PORT: ${{ secrets.PROD_DB_PORT }}
          DB_USER: ${{ secrets.PROD_DB_USER }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          DB_NAME: ${{ secrets.PROD_DB_NAME }}
        run: |
          mkdir -p Auto-Backup
          TIMESTAMP=$(date +%s)
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --no-password | gzip > Auto-Backup/full_backup_$TIMESTAMP.sql.gz
          echo "Backup saved to Auto-Backup/full_backup_$TIMESTAMP.sql.gz"

          # Pass timestamp to next step
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Upload backup to Supabase Storage via REST API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_BACKUP_PROJECT_REF }}  # e.g. sqwzjhoqqgaruscfczaq
          SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_BACKUP_SERVICE_ROLE_KEY }}
          TIMESTAMP: ${{ steps.backup.outputs.timestamp }}
        run: |
          curl -X POST "https://$SUPABASE_URL.supabase.co/storage/v1/object/backups/full/full_backup_$TIMESTAMP.sql.gz" \
            -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
            -H "apikey: $SERVICE_ROLE_KEY" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Auto-Backup/full_backup_$TIMESTAMP.sql.gz

          echo "Backup uploaded to Supabase Storage at backups/full/full_backup_$TIMESTAMP.sql.gz"
