name: Test Supabase Connection with WARP

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudflare WARP
        run: |
          curl https://pkg.cloudflareclient.com/install.sh | sudo bash
          sudo systemctl start warp-svc
          sudo warp-cli connect
          sudo warp-cli status

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Test connection to Supabase
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          psql "host=${{ secrets.DB_HOST }} user=${{ secrets.DB_USER }} dbname=${{ secrets.DB_NAME }} sslmode=require" -c "\dt"
