name: Test Supabase Connection with WARP

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Backup Supabase schema only
        env:
          DB_HOST: aws-0-us-east-2.pooler.supabase.com
          DB_PORT: 5432
          DB_USER: postgres.mlrtlpatqeqchjmafqnm
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: postgres
        run: |
          echo "Starting schema backup..."
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --schema-only > schema_backup_$(date +%s).sql
          echo "Backup complete: schema_backup_$(date +%s).sql"

      - name: Upload schema backup artifact
        uses: actions/upload-artifact@v3
        with:
          name: supabase-schema-backup
          path: schema_backup_*.sql
