name: Test Supabase Backup
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  backup-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Test connection and dump (without saving)
        run: |
          PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_dump \
            -h ${{ secrets.DB_PASSWORD }} pg_dump \
            -h ${{ secrets.DB_HOST }} \
            -U ${{ secrets.DB_USER }} \
            -d postgres \
            --file=/dev/null  # Dumps to void (no storage)
          echo "✅ Backup successful! (Tested connection and pg_dump)"
