name: Backup Supabase Schema

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create schema backup
        env:
          DB_HOST: aws-0-us-east-2.pooler.supabase.com
          DB_PORT: 5432
          DB_USER: postgres.mlrtlpatqeqchjmafqnm
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: postgres
        run: |
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --schema-only > schema_backup.sql

      - name: Commit and push backup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit changes if there are any
          git add schema_backup.sql
          git diff --cached --quiet || git commit -m "Automated schema backup $(date +'%Y-%m-%d %H:%M:%S')"

          # Push to current branch
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
