name: Backup Supabase Schema
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  backup-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PostgreSQL Apt Repository for v17
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

      - name: Install PostgreSQL 17 client tools
        run: sudo apt-get install -y postgresql-client-17

      - name: Backup Supabase schema only
        id: backup
        env:
          DB_HOST: ${{ secrets.PROD_DB_HOST }}
          DB_PORT: ${{ secrets.PROD_DB_PORT }}
          DB_USER: ${{ secrets.PROD_DB_USER }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          DB_NAME: ${{ secrets.PROD_DB_NAME }}
        run: |
          mkdir -p Auto-Backup
          TIMESTAMP=$(date +%s)
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --schema-only \
            --no-password > Auto-Backup/schema_backup_$TIMESTAMP.sql
          echo "Backup saved to Auto-Backup/schema_backup_$TIMESTAMP.sql"

          # Set output timestamp to pass to next step
          echo "::set-output name=timestamp::$TIMESTAMP"

      - name: Upload backup to Supabase Storage
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_BACKUP_SERVICE_ROLE_KEY }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_BACKUP_PROJECT_REF }}
          TIMESTAMP: ${{ steps.backup.outputs.timestamp }}
        run: |
          # Install supabase CLI if not installed
          if ! command -v supabase &> /dev/null; then
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install -g supabase
          fi

          # Upload the backup file to Supabase storage bucket 'backups', folder 'schema'
          supabase storage cp Auto-Backup/schema_backup_$TIMESTAMP.sql backups/schema/schema_backup_$TIMESTAMP.sql --project-ref $SUPABASE_PROJECT_REF

          echo "Backup uploaded to Supabase Storage at backups/schema/schema_backup_$TIMESTAMP.sql"
