name: Test Supabase Connection with WARP

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cloudflare WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ jammy main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp
      - name: Show warp-cli registration help
        run: warp-cli registration --help
