name: Backup Supabase Database (Full + Schema)
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  backup-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PostgreSQL Apt Repository for v17
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

      - name: Install PostgreSQL 17 client tools
        run: sudo apt-get install -y postgresql-client-17 gzip

      - name: Backup full DB (data + schema) compressed and schema-only
        id: backup
        env:
          DB_HOST: ${{ secrets.PROD_DB_HOST }}
          DB_PORT: ${{ secrets.PROD_DB_PORT }}
          DB_USER: ${{ secrets.PROD_DB_USER }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          DB_NAME: ${{ secrets.PROD_DB_NAME }}
        run: |
          mkdir -p Auto-Backup
          TIMESTAMP=$(date +%s)

          # Full dump with data + schema compressed
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --no-password | gzip > Auto-Backup/backup_${TIMESTAMP}_full.sql.gz

          # Schema-only dump uncompressed
          PGPASSWORD=$DB_PASSWORD pg_dump \
            --host=$DB_HOST \
            --port=$DB_PORT \
            --username=$DB_USER \
            --dbname=$DB_NAME \
            --schema-only \
            --no-password > Auto-Backup/backup_${TIMESTAMP}_schema.sql

          echo "Backups created at Auto-Backup/backup_${TIMESTAMP}_full.sql.gz and backup_${TIMESTAMP}_schema.sql"

          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Setup Supabase CLI
        run: |
          curl -L "https://github.com/supabase/cli/releases/latest/download/supabase_$(uname -s)_$(uname -m).tar.gz" -o supabase.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin/
          supabase --version

      - name: Upload backups to Supabase Storage
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_BACKUP_SERVICE_ROLE_KEY }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_BACKUP_PROJECT_REF }}
          TIMESTAMP: ${{ steps.backup.outputs.timestamp }}
        run: |
          # Upload full compressed dump
          supabase storage cp Auto-Backup/backup_${TIMESTAMP}_full.sql.gz backups/backup_${TIMESTAMP}/backup_full.sql.gz --project-ref $SUPABASE_PROJECT_REF

          # Upload schema-only dump
          supabase storage cp Auto-Backup/backup_${TIMESTAMP}_schema.sql backups/backup_${TIMESTAMP}/backup_schema_only.sql --project-ref $SUPABASE_PROJECT_REF

          echo "Backups uploaded to Supabase Storage under backups/backup_${TIMESTAMP}/"
