name: Test Supabase Connection with WARP

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.0

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Test connection to Supabase
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          psql "host=${{ secrets.DB_HOST }} user=${{ secrets.DB_USER }} dbname=${{ secrets.DB_NAME }} sslmode=require" -c "\dt"
