name: Supabase Backup (IPv4 Compatible)
on: workflow_dispatch

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install -y postgresql-client dnsutils

      - name: Backup via Connection Pooler
        run: |
          PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_dump \
            -h ${{ secrets.DB_HOST }} \
            -p 6543 \  # Critical: Pooler port
            -U postgres \
            -d postgres \
            --sslmode=require \
            --file=/dev/null
          echo "✅ Backup successful!"
