name: Supabase Backup (pg_dump)
on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:      # Manual trigger
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Database
        run: |
          apt-get update && apt-get install -y postgresql-client
          PGPASSWORD=${{ secrets.DB_PASSWORD }} pg_dump \
            -h ${{ secrets.DB_HOST }} \
            -U ${{ secrets.DB_USER }} \
            -d postgres \
            -f backup.sql
      - name: Upload Backup
        uses: actions/upload-artifact@v3
        with:
          name: supabase-backup
          path: backup.sql
