name: Supabase Migrations

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Generate migration from Test DB
        run: |
          mkdir -p supabase/migrations      # create folder if missing
          TIMESTAMP=$(date +%s)
          supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} --use-migra > supabase/migrations/${TIMESTAMP}_auto.sql

      - name: Commit migration
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add migration from Test DB"

  deploy-to-prod:
    needs: generate-migration
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Apply migrations to Prod
        run: |
          supabase db push --db-url ${{ secrets.SUPABASE_PROD_DB_URL }}
