name: Supabase Migrations
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Generate migration from Test DB
        run: |
          mkdir -p supabase/migrations
          TIMESTAMP=$(date +%s)
          MIGRATION_FILE="supabase/migrations/${TIMESTAMP}_auto.sql"
          supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} --use-migra > $MIGRATION_FILE

      - name: Commit and push migration safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$MIGRATION_FILE"

          if ! git diff --cached --quiet; then
            git commit -m "chore: add migration from Test DB $(date +'%Y-%m-%d %H:%M:%S')"
            git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No migration changes detected. Skipping commit."
          fi

  deploy-to-prod:
    needs: generate-migration
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Ensure supabase_migrations table exists
        run: |
          psql ${{ secrets.SUPABASE_PROD_DB_URL }} <<'SQL'
          CREATE TABLE IF NOT EXISTS supabase_migrations (
            id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name text NOT NULL,
            hash text NOT NULL,
            executed_at timestamp with time zone DEFAULT now() NOT NULL
          );
          SQL

      - name: Apply migrations to Prod
        run: |
          supabase db push --db-url ${{ secrets.SUPABASE_PROD_DB_URL }}
