name: Supabase Migrations
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Pull latest schema from Test DB
        run: |
          supabase db pull --db-url ${{ secrets.SUPABASE_TEST_DB_URL }}

      - name: Generate incremental migration from Test DB
        run: |
          mkdir -p supabase/migrations
          TIMESTAMP=$(date +%s)
          INCREMENTAL_FILE="supabase/migrations/${TIMESTAMP}_auto.sql"
          supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} --use-migra > "$INCREMENTAL_FILE"

      - name: Commit and push incremental migration safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -s "$INCREMENTAL_FILE" ]; then
            git add "$INCREMENTAL_FILE"
            git commit -m "chore: add incremental migration $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
            git pull --rebase https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No migration changes detected. Skipping commit."
          fi

  deploy-to-prod:
    needs: generate-migration
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Apply migrations to Prod safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p supabase/migrations supabase/baselines

          # Check if Prod already has supabase_migrations table
          EXISTS=$(psql ${{ secrets.SUPABASE_PROD_DB_URL }} -tAc "SELECT 1 FROM information_schema.tables WHERE table_name='supabase_migrations';")

          if [ "$EXISTS" != "1" ]; then
            echo "Empty Prod detected. Creating full baseline from Test DB..."
            TIMESTAMP=$(date +%s)
            BASELINE_FILE="supabase/baselines/${TIMESTAMP}_baseline.sql"
            
            # Dump schema from Test DB
            supabase db dump --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} > "$BASELINE_FILE"

            # Apply baseline directly (NOT committed into migrations/)
            psql ${{ secrets.SUPABASE_PROD_DB_URL }} < "$BASELINE_FILE"
          fi

          echo "Applying incremental migrations to Prod..."
          supabase db push --db-url ${{ secrets.SUPABASE_PROD_DB_URL }}
