name: Supabase Migrations
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Generate migration from Test DB
        run: |
          mkdir -p supabase/migrations
          TIMESTAMP=$(date +%s)
          supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} --use-migra > supabase/migrations/${TIMESTAMP}_auto.sql

      - name: Commit and push migration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add supabase/migrations/*.sql
          git diff --cached --quiet || git commit -m "chore: add migration from Test DB $(date +'%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}

  deploy-to-prod:
    needs: generate-migration
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Supabase CLI
        run: |
          TMP_DIR=$(mktemp -d)
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o $TMP_DIR/supabase.tar.gz
          tar -xzf $TMP_DIR/supabase.tar.gz -C $TMP_DIR
          sudo mv -f $TMP_DIR/supabase /usr/local/bin/supabase
          rm -rf $TMP_DIR

      - name: Apply migrations to Prod (safe baseline)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p supabase/migrations

          # Check if supabase_migrations table exists in Prod
          EXISTS=$(psql ${{ secrets.SUPABASE_PROD_DB_URL }} -tAc "SELECT 1 FROM information_schema.tables WHERE table_name='supabase_migrations';")

          if [ "$EXISTS" != "1" ]; then
            echo "No migrations applied yet. Creating and committing baseline migration..."
            TIMESTAMP=$(date +%s)
            BASELINE_FILE="supabase/migrations/${TIMESTAMP}_baseline.sql"
            supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} --use-migra > $BASELINE_FILE

            # Commit baseline migration to GitHub
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add $BASELINE_FILE
            git commit -m "chore: add baseline migration $(date +'%Y-%m-%d %H:%M:%S')"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "Migrations already exist. Applying incremental migrations..."
          fi

          # Apply all migrations (baseline + incremental)
          supabase db push --db-url ${{ secrets.SUPABASE_PROD_DB_URL }}
