name: Supabase Migrations

on:
  workflow_dispatch: # run manually for now
  push:
    branches: [ "main" ]

jobs:
  generate-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          brew install supabase/tap/supabase


      - name: Generate migration from Test DB
        run: |
          TIMESTAMP=$(date +%s)
          supabase db diff --db-url ${{ secrets.SUPABASE_TEST_DB_URL }} \
            --use-migra > supabase/migrations/${TIMESTAMP}_auto.sql

      - name: Commit migration
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add migration from Test DB"

  deploy-to-prod:
    needs: generate-migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          brew install supabase/tap/supabase


      - name: Apply migrations to Prod
        run: |
          supabase db push --db-url ${{ secrets.SUPABASE_PROD_DB_URL }}
