name: Supabase Backup (IPv4 Forced)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client-15

      - name: Create Backup Directory
        run: mkdir -p backups

      - name: Run pg_dump (Direct IPv4 Connection)
        env:
          PGHOST: db.YOUR_PROJECT_REF.supabase.co
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          PGDATABASE: postgres
        run: |
          # Force IPv4 by disabling IPv6 at system level
          echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf
          
          # Test connection
          psql -c "SELECT 1" || exit 1
          
          # Perform backup
          pg_dump -Fc -Z 9 -f "backups/dump_$(date +%Y%m%d).pgdump"
          
          # Verify backup
          if [ ! -s "backups/dump_$(date +%Y%m%d).pgdump" ]; then
            echo "Backup failed - empty file!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: backups/*.pgdump
