name: Supabase DB Backup (IPv4-safe)

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Dump Supabase Database to SQL
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          # Parse the DB URL manually
          export PGPASSWORD=$(echo "$DB_URL" | sed -E 's/.*\/\/[^:]+:([^@]+)@.*/\1/')
          export PGUSER=$(echo "$DB_URL" | sed -E 's/.*\/\/([^:]+):[^@]+@.*/\1/')
          export PGHOST=$(echo "$DB_URL" | sed -E 's/.*@([^:]+):.*/\1/')
          export PGPORT=$(echo "$DB_URL" | sed -E 's/.*:([0-9]+)\/.*/\1/')
          export PGDATABASE=$(echo "$DB_URL" | sed -E 's/.*\/([^?]+).*/\1/')

          # Force IPv4 for pg_dump
          pg_dump --host="$PGHOST" --port="$PGPORT" --username="$PGUSER" --dbname="$PGDATABASE" --no-password --file=backup.sql --verbose --format=plain

      - name: Upload Backup
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backup.sql
