name: Supabase DB Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          tar -xvzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Dump Supabase DB
        run: |
          supabase db dump \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --file backup.sql

      - name: Upload Backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backup.sql
