name: Supabase DB Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/install.sh | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Verify Supabase CLI
        run: supabase --version

      - name: Backup Supabase DB
        run: |
          supabase db dump \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --file backup.sql

      - name: Upload backup file to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backup.sql
