name: Supabase Backup (Working Version)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install correct PostgreSQL client version
      - name: Add PostgreSQL Repository
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update

      - name: Install PostgreSQL 14 Client (LTS)
        run: sudo apt-get install -y postgresql-client-14

      # 2. Force IPv4 connection
      - name: Configure IPv4 Preference
        run: |
          echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1

      # 3. Create backup
      - name: Run Backup
        env:
          PGHOST: db.mlrtlpatqeqchjmafqnm.supabase.co
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: kSyZVPTQ8vo9Rt0n
          PGDATABASE: postgres
        run: |
          # Test connection
          psql -c "SELECT 1" || exit 1
          
          # Create timestamp
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          
          # Perform backup (custom format with compression)
          pg_dump -Fc -Z 6 -f "supabase_backup_$TIMESTAMP.pgdump"
          
          # Verify backup
          if [ ! -s "supabase_backup_$TIMESTAMP.pgdump" ]; then
            echo "Backup failed - empty file!"
            exit 1
          fi

      # 4. Upload artifact
      - name: Upload Backup
        run: |
          echo "Back--success"
