name: Supabase DB Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: npm install -g supabase@1.158.1

      - name: Backup Supabase DB
        run: |
          supabase db dump \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --file backup.sql

      - name: Upload to Supabase Storage
        run: |
          FILENAME="backup_$(date +%Y-%m-%dT%H-%M-%S).sql"
          supabase storage cp backup.sql "storage://${{ secrets.SUPABASE_BUCKET }}/$FILENAME" \
            --project-url "${{ secrets.SUPABASE_PROJECT_URL }}" \
            --service-role-key "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"
