name: Supabase DB Backup

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          tar -xvzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Login to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Link to Supabase Project
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}  # includes password
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF --db-url $SUPABASE_DB_URL


      - name: Dump Supabase Database
        run: |
          supabase db dump --db-url ${{ secrets.SUPABASE_DB_URL }} --file backup.sql

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backup.sql
